export const country = [
  {value:"country", option:"Select Country"},
  {value:"AF", option:"Afghanistan"},
  {value:"AX", option:"Aland Islands"},
  {value:"AL", option:"Albania"},
  {value:"DZ", option:"Algeria"},
  {value:"AS", option:"American Samoa"},
  {value:"AD", option:"Andorra"},
  {value:"AO", option:"Angola"},
  {value:"AI", option:"Anguilla"},
  {value:"AQ", option:"Antarctica"},
  {value:"AG", option:"Antigua and Barbuda"},
  {value:"AR", option:"Argentina"},
  {value:"AM", option:"Armenia"},
  {value:"AW", option:"Aruba"},
  {value:"AU", option:"Australia"},
  {value:"AT", option:"Austria"},
  {value:"AZ", option:"Azerbaijan "},
  {value:"BS", option:"Bahamas"},
  {value:"BH", option:"Bahrain "},
  {value:"BD", option:"Bangladesh"},
  {value:"BB", option:"Barbados"},
  {value:"BY", option:"Belarus"},
  {value:"BE", option:"Belgium"},
  {value:"BZ", option:"Belize"},
  {value:"BJ", option:"Benin"},
  {value:"BM", option:"Bermuda"},
  {value:"BT", option:"Bhutan"},
  {value:"BO", option:"Bolivia"},
  {value:"BA", option:"Bosnia and Herzegovina"},
  {value:"BW", option:"Botswana"},
  {value:"BV", option:"Bouvet Island"},
  {value:"BR", option:"Brazil"},
  {value:"IO", option:"British Indian Ocean Territory"},
  {value:"BN", option:"Brunei"},
  {value:"BG", option:"Bulgaria"},
  {value:"BF", option:"Burkina Faso"},
  {value:"BI", option:"Burundi"},
  {value:"KH", option:"Cambodia"},
  {value:"CM", option:"Cameroon"},
  {value:"CA", option:"Canada"},
  {value:"CV", option:"Cape Verde"},
  {value:"KY", option:"Cayman Islands"},
  {value:"CF", option:"Central African Republic"},
  {value:"TD", option:"Chad (Tchad)"},
  {value:"CL", option:"Chile"},
  {value:"CN", option:"China"},
  {value:"CX", option:"Christmas Island"},
  {value:"CC", option:"Cocos Islands"},
  {value:"CO", option:"Colombia"},
  {value:"KM", option:"Comoros (Comores)"},
  {value:"CG", option:"Congo"},
  {value:"CD", option:"Congo, Democratic Republic of the"},
  {value:"CK", option:"Cook Islands"},
  {value:"CR", option:"Costa Rica"},
  {value:"HR", option:"Croatia"},
  {value:"CU", option:"Cuba"},
  {value:"CY", option:"Cyprus"},
  {value:"CZ", option:"Czech Republic"},
  {value:"DK", option:"Denmark"},
  {value:"DJ", option:"Djibouti"},
  {value:"DM", option:"Dominica"},
  {value:"DO", option:"Dominican Republic"},
  {value:"EC", option:"Ecuador"},
  {value:"EG", option:"Egypt"},
  {value:"SV", option:"El Salvador"},
  {value:"GQ", option:"Equatorial"},
  {value:"ER", option:"Eritrea"},
  {value:"EE", option:"Estonia"},
  {value:"ET", option:"Ethiopia"},
  {value:"FK", option:"Falkland Islands"},
  {value:"FO", option:"Faroe Islands"},
  {value:"FJ", option:"Fiji"},
  {value:"FI", option:"Finland"},
  {value:"FR", option:"France"},
  {value:"GF", option:"French Guiana"},
  {value:"PF", option:"French Polynesia"},
  {value:"TF", option:"French Southern Territories"},
  {value:"GA", option:"Gabon"},
  {value:"GM", option:"Gambia"},
  {value:"GE", option:"Georgia"},
  {value:"DE", option:"Germany"},
  {value:"GH", option:"Ghana"},
  {value:"GI", option:"Gibraltar"},
  {value:"GR", option:"Greece"},
  {value:"GL", option:"Greenland"},
  {value:"GD", option:"Grenada"},
  {value:"GP", option:"Guadeloupe"},
  {value:"GU", option:"Guam"},
  {value:"GT", option:"Guatemala"},
  {value:"GG", option:"Guernsey"},
  {value:"GN", option:"Guinea"},
  {value:"GW", option:"Guinea-Bissau"},
  {value:"GY", option:"Guyana"},
  {value:"HT", option:"Haiti"},
  {value:"HM", option:"Heard Island and McDonald Islands"},
  {value:"HN", option:"Honduras"},
  {value:"HK", option:"Hong Kong"},
  {value:"HU", option:"Hungary"},
  {value:"IS", option:"Iceland"},
  {value:"IN", option:"India"},
  {value:"ID", option:"Indonesia"},
  {value:"IR", option:"Iran"},
  {value:"IQ", option:"Iraq"},
  {value:"IE", option:"Ireland"},
  {value:"IM", option:"Isle of Man"},
  {value:"IL", option:"Israel"},
  {value:"IT", option:"Italy"},
  {value:"JM", option:"Jamaica"},
  {value:"JP", option:"Japan"},
  {value:"JE", option:"Jersey"},
  {value:"JO", option:"Jordan"},
  {value:"KZ", option:"Kazakhstan"},
  {value:"KE", option:"Kenya"},
  {value:"KI", option:"Kiribati"},
  {value:"KW", option:"Kuwait"},
  {value:"KG", option:"Kyrgyzstan"},
  {value:"LA", option:"Laos"},
  {value:"LV", option:"Latvia"},
  {value:"LB", option:"Lebanon"},
  {value:"LS", option:"Lesotho"},
  {value:"LR", option:"Liberia"},
  {value:"LY", option:"Libya"},
  {value:"LI", option:"Liechtenstein"},
  {value:"LT", option:"Lithuania"},
  {value:"LU", option:"Luxembourg"},
  {value:"MO", option:"Macao"},
  {value:"MK", option:"Macedonia"},
  {value:"MG", option:"Madagascar"},
  {value:"MW", option:"Malawi"},
  {value:"MY", option:"Malaysia"},
  {value:"MV", option:"Maldives"},
  {value:"ML", option:"Mali"},
  {value:"MT", option:"Malta"},
  {value:"MH", option:"Marshall Islands"},
  {value:"MQ", option:"Martinique"},
  {value:"MR", option:"Mauritania"},
  {value:"MU", option:"Mauritius"},
  {value:"YT", option:"Mayotte"},
  {value:"MX", option:"Mexico"},
  {value:"FM", option:"Micronesia"},
  {value:"MD", option:"Moldova"},
  {value:"MC", option:"Monaco"},
  {value:"MN", option:"Mongolia"},
  {value:"ME", option:"Montenegro"},
  {value:"MS", option:"Montserrat"},
  {value:"MA", option:"Morocco"},
  {value:"MZ", option:"Mozambique"},
  {value:"MM", option:"Myanmar"},
  {value:"NA", option:"Namibia"},
  {value:"NR", option:"Nauru"},
  {value:"NP", option:"Nepal"},
  {value:"NL", option:"Netherlands"},
  {value:"AN", option:"Netherlands Antilles"},
  {value:"NC", option:"New Caledonia"},
  {value:"NZ", option:"New Zealand"},
  {value:"NI", option:"Nicaragua"},
  {value:"NE", option:"Niger"},
  {value:"NG", option:"Nigeria"},
  {value:"NU", option:"Niue"},
  {value:"NF", option:"Norfolk Island"},
  {value:"MP", option:"Northern Mariana Islands"},
  {value:"KP", option:"North Korea"},
  {value:"NO", option:"Norway"},
  {value:"OM", option:"Oman"},
  {value:"PK", option:"Pakistan"},
  {value:"PW", option:"Palau"},
  {value:"PS", option:"Palestinian Territories"},
  {value:"PA", option:"Panama"},
  {value:"PG", option:"Papua New Guinea"},
  {value:"PY", option:"Paraguay"},
  {value:"PE", option:"Peru"},
  {value:"PH", option:"Philippines"},
  {value:"PN", option:"Pitcairn"},
  {value:"PL", option:"Poland"},
  {value:"PT", option:"Portugal"},
  {value:"PR", option:"Puerto Rico"},
  {value:"QA", option:"Qatar"},
  {value:"RE", option:"Reunion"},
  {value:"RO", option:"Romania"},
  {value:"RU", option:"Russia"},
  {value:"RW", option:"Rwanda"},
  {value:"SH", option:"Saint Helena"},
  {value:"KN", option:"Saint Kitts and Nevis"},
  {value:"LC", option:"Saint Lucia"},
  {value:"PM", option:"Saint Pierre and Miquelon"},
  {value:"VC", option:"Saint Vincent and the Grenadines"},
  {value:"WS", option:"Samoa"},
  {value:"SM", option:"San Marino"},
  {value:"SA", option:"Saudi Arabia"},
  {value:"SN", option:"Senegal"},
  {value:"RS", option:"Serbia"},
  {value:"CS", option:"Serbia and Montenegro"},
  {value:"SC", option:"Seychelles"},
  {value:"SL", option:"Sierra Leone"},
  {value:"SG", option:"Singapore"},
  {value:"SK", option:"Slovakia"},
  {value:"SI", option:"Slovenia"},
  {value:"SB", option:"Solomon Islands"},
  {value:"SO", option:"Somalia"},
  {value:"ZA", option:"South Africa"},
  {value:"GS", option:"South Georgia and the South Sandwich Islands"},
  {value:"KR", option:"South Korea"},
  {value:"ES", option:"Spain"},
  {value:"LK", option:"Sri Lanka"},
  {value:"SD", option:"Sudan"},
  {value:"SR", option:"Suriname"},
  {value:"SJ", option:"Svalbard and Jan Mayen"},
  {value:"SZ", option:"Swaziland"},
  {value:"SE", option:"Sweden"},
  {value:"CH", option:"Switzerland"},
  {value:"SY", option:"Syria"},
  {value:"TW", option:"Taiwan"},
  {value:"TJ", option:"Tajikistan"},
  {value:"TZ", option:"Tanzania"},
  {value:"TH", option:"Thailand"},
  {value:"TL", option:"Timor-Leste"},
  {value:"TG", option:"Togo"},
  {value:"TK", option:"Tokelau"},
  {value:"TO", option:"Tonga"},
  {value:"TT", option:"Trinidad and Tobago"},
  {value:"TN", option:"Tunisia)"},
  {value:"TR", option:"Turkey"},
  {value:"TM", option:"Turkmenistan"},
  {value:"TC", option:"Turks and Caicos Islands"},
  {value:"TV", option:"Tuvalu"},
  {value:"UG", option:"Uganda"},
  {value:"UA", option:"Ukraine"},
  {value:"AE", option:"United Arab Emirates"},
  {value:"GB", option:"United Kingdom"},
  {value:"US", option:"United States"},
  {value:"UM", option:"United States minor outlying islands"},
  {value:"UY", option:"Uruguay"},
  {value:"UZ", option:"Uzbekistan"},
  {value:"VU", option:"Vanuatu"},
  {value:"VA", option:"Vatican City"},
  {value:"VE", option:"Venezuela"},
  {value:"VN", option:"Vietnam"},
  {value:"VG", option:"Virgin Islands, British"},
  {value:"VI", option:"Virgin Islands, U.S."},
  {value:"WF", option:"Wallis and Futuna"},
  {value:"EH", option:"Western Sahara"},
  {value:"YE", option:"Yemen"},
  {value:"ZM", option:"Zambia"},
  {value:"ZW", option:"Zimbabwe"},
]

export const date = [
  {value:"DD", option:"Date"},
  {value:"1", option:"1"},
  {value:"2", option:"2"},
  {value:"3", option:"3"},
  {value:"4", option:"4"},
  {value:"5", option:"5"},
  {value:"6", option:"6"},
  {value:"7", option:"7"},
  {value:"8", option:"8"},
  {value:"9", option:"9"},
  {value:"10", option:"10"},
  {value:"11", option:"11"},
  {value:"12", option:"12"},
  {value:"13", option:"13"},
  {value:"14", option:"14"},
  {value:"15", option:"15"},
  {value:"16", option:"16"},
  {value:"17", option:"17"},
  {value:"18", option:"18"},
  {value:"19", option:"19"},
  {value:"20", option:"20"},
  {value:"21", option:"21"},
  {value:"22", option:"22"},
  {value:"23", option:"23"},
  {value:"24", option:"24"},
  {value:"25", option:"25"},
  {value:"26", option:"26"},
  {value:"27", option:"27"},
  {value:"28", option:"28"},
  {value:"29", option:"29"},
  {value:"30", option:"30"},
  {value:"31", option:"31"},
]

export const month = [
  
  {value:"month", option:"Month"},
  {value:"jan", option:"January"},
  {value:"feb", option:"February"},
  {value:"mar", option:"March"},
  {value:"apr", option:"April"},
  {value:"May", option:"May"},
  {value:"June", option:"June"},
  {value:"July", option:"July"},
  {value:"August", option:"August"},
  {value:"September", option:"September"},
  {value:"October", option:"October"},
  {value:"November", option:"November"},
  {value:"December", option:"December"},
]

export const year = [
  
  {value:"year", option:"Year"},
  {value:"1990", option:"1990"},
  {value:"1991", option:"1991"},
  {value:"1992", option:"1992"},
  {value:"1993", option:"1992"},
  {value:"1990", option:"1993"},
  {value:"1994", option:"1994"},
  {value:"1995", option:"1995"},
  {value:"1996", option:"1996"},
  {value:"1997", option:"1997"},
  {value:"19918", option:"1998"},
  {value:"19929", option:"1999"},
  {value:"2000", option:"2000"},
  {value:"2001", option:"2001"},
  {value:"2002", option:"2002"},
  {value:"2003", option:"2003"},
  {value:"2004", option:"2004"},
  {value:"2005", option:"2005"},
  {value:"2006", option:"2006"},
  {value:"2007", option:"2007"},
  {value:"2008", option:"2008"},
  {value:"2009", option:"2009"},
  {value:"2010", option:"2010"},
  {value:"2011", option:"2011"},
  {value:"2012", option:"2012"},
  {value:"2013", option:"2013"},
  {value:"2014", option:"2014"},
  {value:"2015", option:"2015"},
  {value:"2016", option:"2016"},
  {value:"2017", option:"2017"},
  {value:"2018", option:"2018"},
  {value:"2019", option:"2019"},
  {value:"2020", option:"2020"},
]